version: 2.1
orbs:
  docker: circleci/docker@1.6.0

jobs:
  test_pytest:
    docker: # executor type
      - image: nipreps/miniconda:py39_2209.01
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PAT

    working_directory: /tmp/tests
    environment:
      - TEST_OUTPUT_DIR: /tmp/test_output
    steps:
      - checkout
      - run:
          name: Get codecov
          command: python -m pip install codecov

      - run:
          name: Run unit tests
          no_output_timeout: 2h
          command: |
            mkdir -p $PWD/artifacts $PWD/summaries
            python -m pytest --junit-xml=/tmp/summaries/pytest.xml \
                   --cov nireports --cov-report xml:/tmp/summaries/unittests.xml \
                   nireports/

      - run:
          name: Submit unit test coverage
          command: |
            cd /tmp/src/nireports
            python -m codecov --file /tmp/tests/summaries/unittests.xml \
                --flags unittests -e CIRCLE_JOB

      - store_artifacts:
          path: /tmp/tests_output

      - store_test_results:
          path: /tmp/tests/summaries/

  build_docs:
    docker: # executor type
      - image: nipreps/miniconda:py39_2209.01
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PAT

    environment:
      - FSLOUTPUTTYPE: NIFTI
      - SUBJECTS_DIR: /tmp/subjects
    steps:
      - checkout
      - run:
          name: Create subjects folder
          command: mkdir -p $SUBJECTS_DIR
      - run:
          name: Install deps
          command: |
            python -m pip install --no-cache-dir -U "pip>=20.3"
            python -m pip install --no-cache-dir -r docs/requirements.txt
            eval "$(pyenv init -)"
      - run:
          name: Install Nireports
          command: |
            python -m pip install .[docs]
      - run:
          name: Build only this commit
          command: |
            BRANCH=$( echo $CIRCLE_BRANCH | sed 's+/+_+g' )
            make -C docs SPHINXOPTS="-W" BUILDDIR="/tmp/docs" OUTDIR=${CIRCLE_TAG:-$BRANCH} html
      - store_artifacts:
          path: /tmp/docs

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_pytest:
          context:
            - nipreps-common
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /docs?\/.*/

      - build_docs:
          filters:
            branches:
              ignore:
                - /tests?\/.*/
            tags:
              only: /.*/
